// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAGasMcvCqGvGdo1sY2MPl_hyvoslR0xs',
    appId: '1:770509378194:web:117fae41dad7df270a8c4b',
    messagingSenderId: '770509378194',
    projectId: 'kilifarm-5bb48',
    authDomain: 'kilifarm-5bb48.firebaseapp.com',
    storageBucket: 'kilifarm-5bb48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMpc4rxQM3L1gS0vC1p26NnqG6S_1GFE',
    appId: '1:770509378194:android:24ea5336b10160080a8c4b',
    messagingSenderId: '770509378194',
    projectId: 'kilifarm-5bb48',
    storageBucket: 'kilifarm-5bb48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALADXMvl33ZgJtNuidpl1Jwus89Rp4oz0',
    appId: '1:770509378194:ios:c87625a94b2e7f760a8c4b',
    messagingSenderId: '770509378194',
    projectId: 'kilifarm-5bb48',
    storageBucket: 'kilifarm-5bb48.firebasestorage.app',
    iosBundleId: 'com.example.kilifarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALADXMvl33ZgJtNuidpl1Jwus89Rp4oz0',
    appId: '1:770509378194:ios:c87625a94b2e7f760a8c4b',
    messagingSenderId: '770509378194',
    projectId: 'kilifarm-5bb48',
    storageBucket: 'kilifarm-5bb48.firebasestorage.app',
    iosBundleId: 'com.example.kilifarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAGasMcvCqGvGdo1sY2MPl_hyvoslR0xs',
    appId: '1:770509378194:web:8b53be94677e92c20a8c4b',
    messagingSenderId: '770509378194',
    projectId: 'kilifarm-5bb48',
    authDomain: 'kilifarm-5bb48.firebaseapp.com',
    storageBucket: 'kilifarm-5bb48.firebasestorage.app',
  );
}
